# Generated by Django 3.0.7 on 2020-06-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(0, 'each'), (1, 'gram')], default=0),
        ),
    ]
