# Generated by Django 3.0.7 on 2020-06-19 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Prefer Not To Answer')], default='N/A', max_length=3)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'people',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userApp.Person')),
                ('addresses', models.ManyToManyField(to='locationApp.Address')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['created_date'],
            },
        ),
    ]
