# Generated by Django 3.0.7 on 2020-06-18 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogueApp', '0002_auto_20200617_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('unique_cart_id', models.CharField(max_length=500)),
                ('cart_status', models.IntegerField(choices=[(0, 'Open'), (1, 'CheckedOut')], default=0)),
            ],
            options={
                'db_table': 'carts',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartApp.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueApp.Product')),
            ],
            options={
                'db_table': 'cart_imtes',
                'ordering': ['created_date'],
            },
        ),
    ]
