# Generated by Django 3.0.7 on 2020-06-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
