# Generated by Django 3.0.7 on 2020-06-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogueApp', '0002_auto_20200617_2115'),
        ('userApp', '0001_initial'),
        ('locationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_item_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('order_status', models.IntegerField(choices=[(0, 'Canceled'), (1, 'Submitted'), (2, 'Completed'), (3, 'Processing')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.Customer')),
                ('delivery_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locationApp.Address')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogueApp.Product')),
            ],
            options={
                'db_table': 'order_items',
                'ordering': ['created_date'],
            },
        ),
    ]
